version: "3"

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200

    logstash:
        image: docker.elastic.co/logstash/logstash:7.10.0
        depends_on:
            - elasticsearch

    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.0
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
