#!/usr/bin/env ruby
#^syntax detection

forge 'https://forgeapi.puppetlabs.com'

# puppet support
mod 'puppet-archive'
mod 'puppet-yum'
mod 'puppetlabs-yumrepo_core'
mod 'puppetlabs-apt'
mod 'darin-zypprepo'

# common and deps
mod 'ghoneycutt-common'
mod 'ghoneycutt-ntp'
mod 'ghoneycutt-dnsclient'
mod 'ghoneycutt-pam'
mod 'trlinkin-nsswitch'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-concat'

# outgoing mail and deps
mod 'camptocamp-postfix'
mod 'puppet-alternatives'
mod 'puppetlabs-mailalias_core'

# system
mod 'saz-sudo'
mod 'puppet-rsyslog'
mod 'puppet-selinux'

# security
mod 'thbe-rkhunter'
mod 'sensson-csf'

# languages
mod 'puppetlabs-java'
mod 'puppetlabs-ruby'
mod 'puppet-nodejs'
mod 'puppet-python'
mod 'bodgit-scl'

# application servers
mod 'puppetlabs-apache'

# puppet masters
mod 'puppet-puppetserver'
mod 'puppet-puppetboard'
mod 'camptocamp-augeas'
mod 'puppetlabs-puppetserver_gem'
mod 'puppetlabs-puppetdb'
mod 'puppetlabs-postgresql'
mod 'puppetlabs-inifile'
mod 'stahnma-epel'
mod 'herculesteam-augeasproviders_sysctl'
mod 'herculesteam-augeasproviders_core'
mod 'herculesteam-augeasproviders_ssh'

# r10k (and its deps)
mod 'puppet-r10k'
mod 'abrader-gms'
mod 'puppetlabs-git'

# vcsrepo for git
mod 'puppetlabs-vcsrepo'
