Vagrant.configure("2") do |config|
  # hypervisor
  config.vm.provider "virtualbox" do |vmp|
    vmp.memory = 2048
    vmp.cpus = 2
  end

  # base OS
  config.vm.box = "generic/centos7"

  # machine specific
  config.vm.hostname = "startsh.vagrant"
  config.vm.network "private_network", ip: "192.168.23.10"

  # transfer a script and execute at provision time
  config.vm.provision "shell", path: "../../shared/scripts/bootco7.sh"
end