Vagrant.configure("2") do |config|
  # hypervisor
  config.vm.provider "virtualbox" do |vmp|
    vmp.memory = 4096
    vmp.cpus = 2
  end

  # base OS
  config.vm.box = "generic/centos7"

  # machine specific
  config.vm.hostname = "single.vagrant"
  config.vm.network "private_network", ip: "192.168.23.30"

  # run install script
  # config.vm.provision "shell", path: "../../../terraform/tutorial/11-kubernetes-host/scripts/install_rancher_server.sh"
  config.vm.provision "shell", path: "../../../terraform/tutorial/11-kubernetes-host/scripts/install_rancherd.sh"
end
