Vagrant.configure("2") do |config|
  # hypervisor
  config.vm.provider "virtualbox" do |vmp|
    vmp.memory = 2048
    vmp.cpus = 2
  end

  # base OS
  config.vm.box = "generic/centos7"

  # machine specific
  config.vm.hostname = "sharedfolder.vagrant"
  config.vm.network "private_network", ip: "192.168.23.10"

  # make a local folder available within the VM
  config.vm.synced_folder "../../../eyaml/keys", "/srv/keys"
end