Vagrant.configure("2") do |config|
  # hypervisor
  config.vm.provider "virtualbox" do |vmp|
    vmp.memory = 1024
    vmp.cpus = 1
  end

  # base OS
  config.vm.box = "generic/centos7"

  # machine specific
  config.vm.hostname = "single.vagrant"
  config.vm.network "private_network", ip: "192.168.23.10"
end