Vagrant.configure("2") do |config|
  # hypervisor
  config.vm.provider "virtualbox" do |vmp|
    vmp.memory = 2048
    vmp.cpus = 2
  end

  config.vm.define "es1", primary: true do |c|
    c.vm.hostname = "es1.vagrant"
    c.vm.network "private_network", ip: "192.168.23.21"
  end

  config.vm.define "es2" do |c|
    c.vm.hostname = "es2.vagrant"
    c.vm.network "private_network", ip: "192.168.23.22"
  end

  # base OS
  config.vm.box = "generic/centos7"

  # common across all VMs
  config.vm.synced_folder "../../../eyaml/keys", "/srv/keys"
  config.vm.provision "shell", path: "../../shared/scripts/bootco7.sh"

  # kick off puppet run
  config.vm.provision "puppet" do |puppet|
    puppet.environment_path = "../../../puppet/environments"
    puppet.environment = "workstream"
    puppet.module_path = ["../../../puppet/modules","../../../puppet/environments/shared/modules","../../../puppet/environments/workstream/modules"]
    puppet.options = "-t"
  end
end